// Mock data for development — will be replaced with DB queries

export const categories = [
    { id: "1", name: "Surgical Instruments", slug: "surgical-instruments", icon: "🔪", image: "/categories/surgical.jpg" },
    { id: "2", name: "Diagnostic Equipment", slug: "diagnostic-equipment", icon: "🩺", image: "/categories/diagnostic.jpg" },
    { id: "3", name: "Hospital Furniture", slug: "hospital-furniture", icon: "🛏️", image: "/categories/furniture.jpg" },
    { id: "4", name: "PPE & Safety", slug: "ppe-safety", icon: "🧤", image: "/categories/ppe.jpg" },
    { id: "5", name: "Wound Care", slug: "wound-care", icon: "🩹", image: "/categories/wound.jpg" },
    { id: "6", name: "Respiratory Care", slug: "respiratory-care", icon: "💨", image: "/categories/respiratory.jpg" },
    { id: "7", name: "Orthopedic", slug: "orthopedic", icon: "🦴", image: "/categories/orthopedic.jpg" },
    { id: "8", name: "Laboratory", slug: "laboratory", icon: "🔬", image: "/categories/lab.jpg" },
    { id: "9", name: "Dental Equipment", slug: "dental-equipment", icon: "🦷", image: "/categories/dental.jpg" },
    { id: "10", name: "Consumables", slug: "consumables", icon: "💊", image: "/categories/consumables.jpg" },
];

export const products = [
    {
        id: "1",
        name: "Professional Surgical Scissors — Titanium Coated",
        slug: "professional-surgical-scissors-titanium",
        description: "Premium titanium-coated surgical scissors with ergonomic grip. Designed for precision cutting in surgical environments. Autoclavable and corrosion-resistant.",
        images: ["/products/scissors-1.jpg", "/products/scissors-2.jpg"],
        b2cPrice: 4500,
        b2bPrice: 3200,
        stock: 150,
        featured: true,
        trending: true,
        flashDeal: false,
        category: categories[0],
        categoryId: "1",
    },
    {
        id: "2",
        name: "Digital Stethoscope — Pro Edition",
        slug: "digital-stethoscope-pro-edition",
        description: "Advanced digital stethoscope with noise cancellation technology. Bluetooth connectivity for recording and analysis. Premium acoustic quality.",
        images: ["/products/stethoscope-1.jpg"],
        b2cPrice: 18500,
        b2bPrice: 14000,
        stock: 75,
        featured: true,
        trending: false,
        flashDeal: true,
        flashDealEnd: new Date("2026-03-01"),
        category: categories[1],
        categoryId: "2",
    },
    {
        id: "3",
        name: "ICU Patient Monitor — 7 Parameter",
        slug: "icu-patient-monitor-7-parameter",
        description: "Multi-parameter patient monitor featuring ECG, SpO2, NIBP, temperature, respiration, IBP, and CO2 monitoring. 12.1-inch HD touchscreen display.",
        images: ["/products/monitor-1.jpg"],
        b2cPrice: 285000,
        b2bPrice: 225000,
        stock: 20,
        featured: true,
        trending: true,
        flashDeal: false,
        category: categories[1],
        categoryId: "2",
    },
    {
        id: "4",
        name: "Adjustable Hospital Bed — Electric",
        slug: "adjustable-hospital-bed-electric",
        description: "Fully electric hospital bed with 4-section adjustment. Side rails, CPR quick-release, and Trendelenburg/reverse positioning. 250kg weight capacity.",
        images: ["/products/bed-1.jpg"],
        b2cPrice: 195000,
        b2bPrice: 155000,
        stock: 12,
        featured: false,
        trending: false,
        flashDeal: false,
        category: categories[2],
        categoryId: "3",
    },
    {
        id: "5",
        name: "N95 Respirator Mask — Pack of 50",
        slug: "n95-respirator-mask-pack-50",
        description: "NIOSH-approved N95 respirator masks. Multi-layer filtration with adjustable nose clip. Individually packaged for sterility.",
        images: ["/products/mask-1.jpg"],
        b2cPrice: 3500,
        b2bPrice: 2200,
        stock: 500,
        featured: false,
        trending: true,
        flashDeal: true,
        flashDealEnd: new Date("2026-02-28"),
        category: categories[3],
        categoryId: "4",
    },
    {
        id: "6",
        name: "Portable Pulse Oximeter — OLED Display",
        slug: "portable-pulse-oximeter-oled",
        description: "Fingertip pulse oximeter with bright OLED display. SpO2 and pulse rate monitoring with waveform. Auto power-off and low battery indicator.",
        images: ["/products/oximeter-1.jpg"],
        b2cPrice: 2800,
        b2bPrice: 1800,
        stock: 300,
        featured: true,
        trending: true,
        flashDeal: false,
        category: categories[1],
        categoryId: "2",
    },
    {
        id: "7",
        name: "Autoclave Sterilizer — 22L Capacity",
        slug: "autoclave-sterilizer-22l",
        description: "Class B autoclave sterilizer with 22-liter chamber. Pre-vacuum and post-vacuum drying cycles. LCD display with error diagnostics.",
        images: ["/products/autoclave-1.jpg"],
        b2cPrice: 165000,
        b2bPrice: 130000,
        stock: 8,
        featured: false,
        trending: false,
        flashDeal: false,
        category: categories[7],
        categoryId: "8",
    },
    {
        id: "8",
        name: "Disposable Surgical Gloves — Box of 100",
        slug: "disposable-surgical-gloves-100",
        description: "Powder-free latex surgical gloves. Textured fingertips for enhanced grip. Sterile, individually paired. Available in sizes S-XL.",
        images: ["/products/gloves-1.jpg"],
        b2cPrice: 1800,
        b2bPrice: 1100,
        stock: 1000,
        featured: false,
        trending: false,
        flashDeal: true,
        flashDealEnd: new Date("2026-02-20"),
        category: categories[3],
        categoryId: "4",
    },
];

export const heroSlides = [
    {
        id: 1,
        title: "Premium Surgical Instruments",
        subtitle: "Precision engineered for healthcare professionals",
        cta: "Shop Now",
        href: "/products?category=surgical-instruments",
        gradient: "from-primary-900 via-primary-800 to-surface-900",
    },
    {
        id: 2,
        title: "Advanced Diagnostic Equipment",
        subtitle: "State-of-the-art monitoring & diagnostic solutions",
        cta: "Explore Range",
        href: "/products?category=diagnostic-equipment",
        gradient: "from-surface-900 via-primary-900 to-primary-800",
    },
    {
        id: 3,
        title: "Flash Deals — Up to 40% Off",
        subtitle: "Limited time offers on essential medical supplies",
        cta: "View Deals",
        href: "/products?flashDeal=true",
        gradient: "from-accent-700 via-accent-600 to-primary-800",
    },
];
